{"name": "test_failed_login[payload0]", "status": "failed", "statusDetails": {"message": "AssertionError: ERROR NOT FOUND\nassert ('error' in {'token': 'QpwL5tke4Pnpja7X4'})", "trace": "tests\\test_api.py:32: in test_failed_login\n    assert \"error\" in data and data[\"error\"], \"ERROR NOT FOUND\"\nE   AssertionError: ERROR NOT FOUND\nE   assert ('error' in {'token': 'QpwL5tke4Pnpja7X4'})"}, "parameters": [{"name": "payload", "value": "{'email': 'eve.holt@reqres.in', 'password': 'wrongpassword'}"}], "start": 1740047868904, "stop": 1740047869820, "uuid": "b35b38aa-676f-4fb4-9bf0-66946c40acda", "historyId": "8c1b59774e9b816f6438ec8616423457", "testCaseId": "fb5fba7635612fba64f4f1ae869263b0", "fullName": "tests.test_api#test_failed_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "LAPTOP-3FDQQ998"}, {"name": "thread", "value": "72552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}